%% Parameters
env_parameters = struct('NEIGHBOR_THRESHOLD', 100.0, ... % 0.05, ...        % Geo-I Neighbor distance threshold 
                        'NR_TASK', 50, ...                                  % Number of tasks
                        'EPSILON', 10.0, ...                                % Privacy budget epsilon
                        'GAMMA', 20.0, ...                                  % Relevant location distance threshold: default 20
                        'nr_loc_selected', 100, ...                         % 
                        'longitude_min', 0, ...                             % 
                        'longitude_max', 0, ...
                        'latitude_min', 0, ...
                        'latitude_max', 0, ...
                        'node_target', [], ...
                        'node_target_selected', [], ...
                        'scale', 1.0, ...
                        'G', [], ...
                        'G_mDP', [], ...
                        'longitude_raw', [], ...
                        'latitude_raw', [], ...
                        'longitude', [], ...
                        'latitude', [], ...
                        'longitude_selected', [], ...
                        'latitude_selected', [], ...
                        'osmid', []); 